import = ["~/dotfiles/home/.config/alacritty/themes/onedark.toml"]

[window]
decorations = "Full"
startup_mode = "Maximized"
dynamic_title = false
opacity = 0.60


[font]
size = 16.0
normal = { family = "IosevkaTermSlab Nerd Font Mono"}
italic = { style = "Light Italic" }
