import = ["~/dotfiles/home/.config/alacritty/themes/onedark.toml"]

[window]
decorations = "Full"
startup_mode = "Maximized"
dynamic_title = false
opacity = 0.60


[font]
size = 12.0
normal = { family = "GeistMono Nerd Font", style = "SemiBold" }
italic = { style = "Light Italic" }
