import = ["~/dotfiles/home/.config/alacritty/themes/dracula.toml"]

[window]
decorations = "Full"
startup_mode = "Maximized"
dynamic_title = false


[font]
size = 12.0
normal = { family = "GeistMono Nerd Font", style = "SemiBold" }
italic = { style = "Light Italic" }
