import = ["~/.config/alacritty/themes/themes/kanagawa_dragon.toml"]

[window]
decorations = "Full"
startup_mode = "Fullscreen"
dynamic_title = false
opacity = 0.55
blur = true


[font]
size = 12.0
normal = { family = "IntoneMono Nerd Font Mono", style = "Regular" }
italic = { style = "Light Italic" }
